pipeline {
  agent any
  stages {
    stage('Pull Update') {
      steps {
        echo 'pull update'
      }
    }
    stage("Browser Test"){
      parallel {
      stage('Chrome') {
      steps {
        echo 'chrome test'
      }
    }
    stage('Firefox') {
      steps {
        echo 'firefox test'
      }
    }
    stage('Internet Explorer') {
      steps {
        echo 'ie test'
      }
    }
  }
  }

    stage('Security Test') {
      steps {
        echo 'security testing'
      }
    }

    stage('Deploy') {
      steps {
        echo 'deploy'
      }
    }


     stage("Notify"){
      parallel {
      stage('Update Jira') {
      steps {
        echo 'Update jira'
      }
    }
    stage('Send Mail') {
      steps {
        echo 'send mail'
      }
    }
    stage('Send IM') {
      steps {
        echo 'send im'
      }
    }
  }
  }
  }
}